sudo: required
services:
   - docker

before_install:
   - docker build -t aws22422/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true aws22422/docker-react npm run test -- --coverage

deploy:
   provider: elasticbeanstalk
   region: “us-east-1”
   app: “Docker”
   env: “Docker-env”
      bucket_name: “elasticbeanstalk-us-east-1-493993456983”
   bucket_path: “Docker”
   on:
      branch: main

   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: “$AWS_SECRET_KEY”

